# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Jan21.github.io/character_recognition_gen/"

git_url = "https://github.com/Jan21/character_recognition_gen/tree/master/"

def custom_doc_links(name): return None
